### ISSUE TITLE
Error when hitting save and publish on some slices

### ISSUE THREAD

**Issue by bendubuisson** [heyday/silverstripe-slices#1] opened 2015-09-24 03:07 UTC
We have a base slice `ContentSlice` that extends Slice and then some of them extend that base slice.
For those slices, I need to Save, then Save and publish, otherwise I get an error:
`Uncaught Exception: Object->__call(): the method 'publish' does not exist on 'ContentSlice'`

**Comment by bendubuisson** [comment] 2015-09-24 03:08
If I were to hit Save and Publish twice it works, seems like it needs to be saved first...

**Comment by stecman** [comment] 2015-09-28 01:58
This has popped up on a few projects that are using the 1.0 alpha. It's caused by the ClassName of a DataObject changing (via `DataObject::setClassName`) in `Slice::setClassNameByTemplate`. This behaviour worked fine in the 0.x version, so something has either been broken in this module during the 1.0 rework, or a recent version of SilverStripe has changed.

This same error _message_ came up about two years ago in the 0.x version, and was fixed with code that's still present: originally fixed in project code, [then in adaptivecontent](https://github.com/heyday/silverstripe-adaptivecontent/blob/9dd85f121334c49231609d2792d4d3baceaa340a/src/Traits/ClassBySecondaryIdentifierTrait.php#L42-L47), and [now part of `Slice`](https://github.com/heyday/silverstripe-slices/blob/376909c80b2f5258212c1fa0ab34d19d0c256a2e/code/DataObjects/Slice.php#L349-L355).

If you want to debug this, checking if the 0.x version of this module works correctly with the latest SilverStripe 3.1 release would be a good start.

**Closed as completed** 2015-10-21 22:58 UTC
Labels: bug
